### ISSUE TITLE
Deleting pastes

### ISSUE THREAD

**Issue by SPYmesu** [MinusKube/JPastee#1]
Hey!
Can you please add method to delete existing paste please?
paste.ee store all pastes 4 weeks and it is too long :c

**Comment by MinusKube** [comment]
Hi, it's already possible using the [`JPastee#deletePaste(String)`](https://github.com/MinusKube/JPastee/blob/master/src/main/java/fr/minuskube/pastee/JPastee.java#L113) method! :D

**Comment by MinusKube** [comment]
(But I just realized the deletePaste is not working, gonna fix it now!)

**Comment by MinusKube** [comment]
Okay I fixed the bug and released it! But the delete paste endpoint on the API is currently broken, so it's not really possible to delete pastes.

If you want this to be fixed, you'll need to ask the paste.ee developer for it, you can join him on Discord: https://discord.gg/WQJ8z5G
